name: terraform_configuraration
on: 
  workflow_dispatch: 
    inputs: 
    environment:
        description: "Select Environment"
        required: true
        type: choice
        options:
          - dev
          - QA
          - UAT
          - prod

jobs:
  terraform:
    name: terraform plan and apply
    runs-on: self-hosted
    environment: ${{ inputs.environment }}
    steps:
      - name: checkout_code
        uses: actions/checkout@v4
      - name: terraform_setuop
        uses: hashicorp/setup-terraform@v3
      - name: Azure Login
        uses: azure/login@v2
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: terraform_init
        working-directory: Env/${{ inputs.environment }}
        run: terraform init

      - name: terraform_validate
        working-directory: Env/${{ inputs.environment }}
        run: terraform validate

      - name: terraform_plan
        working-directory: Env/${{ inputs.environment }}
        run: terraform plan 

      - name: terraform apply
        working-directory: Env/${{ inputs.environment }}
        run: terraform apply -auto-approve
